title: Idena Runner Bash Script
description: "Bash Script implementation of the Idena network node installation wizard with the possibility to install multiple idena-go instances (1 user â€” 1 instance)"
logo: /assets/img/idena_runner_man_logo.png
intro: "https://raw.githubusercontent.com/ltraveler/ltraveler/main/images/intro/idena_runner%400%2C25x.webp"
baseurl: "idena-runner-man"
google_site_verification: Y3sUQ3V7QpUpjFq4mrsm-BCevZBncXL96-3dxL58cEk
show_downloads: true
show_copyrights: false
plugins:
google_analytics: G-S4M1CN0DM6
theme: jekyll-theme-minimal
github:
  zip_url: https://github.com/ltraveler/idena-runner/zipball/main
  tar_url: https://github.com/ltraveler/idena-runner/tarball/main
  repository_url: https://github.com/ltraveler/idena-runner
  
  en:
  label: English
  icon: ğŸ‡¬ğŸ‡§
  read_en: "Read it in"
  ru:
  label: Ğ ÑƒÑÑĞºĞ¸Ğ¹
  icon: ğŸ‡·ğŸ‡º
  read_ru: "Ğ§Ğ¸Ñ‚Ğ°Ñ‚ÑŒ Ğ½Ğ°"
